#[[plugins]]
#repo = 'w0rp/ale'
#hook_post_source = '''
#" エラー行に表示するマーク
#let g:ale_sign_error = '⨉'
#let g:ale_sign_warning = '⚠'
#" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
#let g:ale_echo_msg_format = '[%linter%] %code: %%s [%severity%]'
#" エラー表示の列を常時表示
#let g:ale_sign_column_always = 1
#
#let g:ale_lint_on_enter = 1
#let g:ale_lint_on_save = 1
#let g:ale_fix_on_save = 1
#
#" lint結果をロケーションリストとQuickFixには表示しない
#" 出てると結構うざいしQuickFixを書き換えられるのは困る
#let g:ale_set_loclist = 0
#let g:ale_set_quickfix = 0
#let g:ale_open_list = 0
#let g:ale_keep_list_window_open = 0
#
#" ALE用プレフィックス
#nmap [ale] <Nop>
#map <C-k> [ale]
#" エラー行にジャンプ
#nmap <silent> [ale]<C-P> <Plug>(ale_previous)
#nmap <silent> [ale]<C-N> <Plug>(ale_next)
#'''
#

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_post_source = '''
let g:airline_powerline_fonts = 1
let g:airline_theme = 'badwolf'
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
'''

# Elixir
[[plugins]]
repo = 'elixir-editors/vim-elixir'
# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_post_source = '''
if empty(globpath(&rtp, 'autoload/lsp.vim'))
  finish
endif

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> <f2> <plug>(lsp-rename)
  inoremap <expr> <cr> pumvisible() ? "\<c-y>\<cr>" : "\<cr>"
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
command! LspDebug let lsp_log_verbose=1 | let lsp_log_file = expand('~/lsp.log')

let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_text_edit_enabled = 1
let g:lsp_highlights_enabled = 1
let g:lsp_textprop_enabled = 1
let g:lsp_virtual_text_enabled = 1
let g:lsp_highlight_references_enabled = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
[[plugins]]
repo = 'mattn/vim-goimports'
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'


[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
